docker-build-master:
  stage: build
  image: ubuntu:18.04
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://localhost:2375/
    COLLABORA_ONLINE_REPO: https://github.com/stuvusIT/CollaboraOnline.git
    TZ: Europe/Berlin
    DOCKERHUB_REPO: $CI_REGISTRY_IMAGE
    DOCKER_HUB_TAG: latest
  before_script:
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    - apt-get update && apt-get -y install git sudo build-essential wget libssl-dev automake pkg-config autoconf libfontconfig1-dev gperf libkrb5-dev python3-lxml libpng-dev libcap-dev libtool m4 libcppunit-dev libcppunit-doc flex bison zip gettext libx11-dev libpcap-dev libcap2-bin python3-polib libpam0g-dev curl libssl-dev fontconfig
    - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sudo sh get-docker.sh
    - cd docker/from-source
    - chmod +x build.sh
    - adduser stuvus --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
    - 'echo "stuvus     ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers'
    - sudo usermod -aG docker stuvus
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - 'su -c "bash build.sh" stuvus'
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master

docker-build:
  stage: build
  image: ubuntu:18.04
  services:
    - docker:18.09.7-dind
  variables:
    DOCKER_DRIVER: overlay
    DOCKER_HOST: tcp://localhost:2375/
    COLLABORA_ONLINE_REPO: https://github.com/stuvusIT/CollaboraOnline.git
    TZ: Europe/Berlin
    DOCKERHUB_REPO: $CI_REGISTRY_IMAGE
    DOCKER_HUB_TAG: $CI_COMMIT_REF_SLUG
  before_script:
    - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
    - apt-get update && apt-get -y install git sudo build-essential wget libssl-dev automake pkg-config autoconf libfontconfig1-dev gperf libkrb5-dev python3-lxml libpng-dev libcap-dev libtool m4 libcppunit-dev libcppunit-doc flex bison zip gettext libx11-dev libpcap-dev libcap2-bin python3-polib libpam0g-dev curl libssl-dev fontconfig
    - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sudo sh get-docker.sh
    - cd docker/from-source
    - chmod +x build.sh
    - adduser stuvus --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
    - 'echo "stuvus     ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers'
    - sudo usermod -aG docker stuvus
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - 'su -c "bash build.sh" stuvus'
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
